# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5aebd5d71ed5fab81b8bd72a5f79314624e5a270a1df0347e262f507eaa1469cc7c73a1af860336bd6c8e96fffc804f8bb732d5151c010211a48d2042dd994

test:
  secret_key_base: 271cc5a51a3a91e2dd419532ce66886a3e99ca4f19aea1451bfee227b399b14d08eaf70e3963a1b845e483b1f0cf69f2666577da831546bdc5d1ef71eae341a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
